[project]
name = "openadapt"
version = "0.0.0"

authors = [
    { name = "Mustafa Abdulrahman", email = "mustafa@openadapt.ai" },
    { name = "Richard Abrich", email = "richard.abrich@mldsai.com" },
    { name = "Avid Eslami", email = "avid@openadapt.ai" },
    { name = "Andrew Gorton", email = "andrew.gorton@mail.utoronto.ca" },
    { name = "Krish Patel", email = "krish@openadapt.ai" },
    { name = "Dian Rong", email = "dian@openadapt.ai" },
    { name = "Aaron Shah", email = "aaron@openadapt.ai" },
    { name = "Jesica Susanto", email = "jesica@openadapt.ai" },
    { name = "Angela Zhuo", email = "angela@openadapt.ai" },
    { name = "Owais Zahid", email = "owais@openadapt.ai" }
]

description = "AI-First Process Automation with Transformers"
readme = "README.md"
requires-python = ">=3.10"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/MLDSAI/OpenAdapt"
"Bug Tracker" = "https://github.com/MLDSAI/OpenAdapt/issues"

[tool.semantic_release]
version_variable = [
    "openadapt/__init__.py:__version__"
]
version_toml = [
    "pyproject.toml:project.version"
]
major_on_zero = false
branch = "main"
commit_subject = "chore(release): v{version}"
commit_version_number = true
upload_to_PyPI = false
upload_to_release = true
upload_to_repository = false
repository_url = "https://upload.pypi.org/legacy/"
build_command = "python3 -m pip install --upgrade build && python3 -m build"