[project]
name = "openadapt"
version = "0.0.2"
authors = [
  { name="MLDSAI Inc.", email="richard.abrich@mldsai.com" },
]
description = "AI-First Process Automation with Transformers"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/MLDSAI/OpenAdapt"
"Bug Tracker" = "https://github.com/MLDSAI/OpenAdapt/issues"

[tool.semantic_release]
version_variable = [
    "openadapt/__init__.py:__version__"
]
version_toml = [
    "pyproject.toml:tool.poetry.version"
]
version_pattern = [
    "README.md:rev: v{version}",
]
major_on_zero = false
branch = "main"
upload_to_PyPI = true
upload_to_release = true
build_command = "pip install poetry && poetry build"